# Generated by Django 4.1.4 on 2022-12-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(default='no description', max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(default='no genre', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(default='no platform', max_length=100),
        ),
    ]
