# Generated by Django 4.1.4 on 2022-12-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg_app', '0002_alter_game_description_alter_game_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(default='no description', max_length=1000),
        ),
    ]
