# Generated by Django 4.1.4 on 2022-12-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg_app', '0003_alter_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video_title',
            field=models.CharField(default='no video title', max_length=250),
        ),
    ]
