# Generated by Django 4.1.4 on 2022-12-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg_app', '0004_game_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='star_rating',
            field=models.IntegerField(default=1),
        ),
    ]
