# Generated by Django 4.1.4 on 2022-12-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg_app', '0006_alter_game_star_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
    ]
