# Generated by Django 4.1.4 on 2022-12-30 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gg_app', '0008_alter_post_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
