# Generated by Django 4.1.4 on 2022-12-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg_app', '0009_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
