# Generated by Django 4.1.4 on 2023-01-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg_app', '0019_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='color',
            field=models.CharField(default='no color', max_length=250),
        ),
    ]
