# Generated by Django 4.1.4 on 2023-01-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg_app', '0020_game_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gp_photo_one',
            field=models.CharField(default='no photo', max_length=250),
        ),
        migrations.AddField(
            model_name='game',
            name='gp_photo_three',
            field=models.CharField(default='no photo', max_length=250),
        ),
        migrations.AddField(
            model_name='game',
            name='gp_photo_two',
            field=models.CharField(default='no photo', max_length=250),
        ),
    ]
